package:
  name: perutils
  version: 0.0.23
source:
  sha256: e9fc32f0b1aa0ccb5be0510462372dbea399538d1f6b88066c6b08ef4bacdbad
  url: https://files.pythonhosted.org/packages/d8/e5/d56ab013e43671daedc32828eed1fb02de3e80fa0b1af5636b19ecbfd229/perutils-0.0.23.tar.gz
about:
  dev_url: https://Isaac.Flath@gmail.com.github.io
  doc_url: https://Isaac.Flath@gmail.com.github.io
  home: https://Isaac.Flath@gmail.com.github.io
  license: Apache Software
  license_family: APACHE
  summary: Isaacs personal utils
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - Isaac.Flath@gmail.com
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - fastai
  run:
  - pip
  - python
  - packaging
  - pandas
  - fastai
test:
  imports:
  - perutils
