package:
  name: perutils
  version: 0.0.22
source:
  sha256: 95065301eb212a518963fb24a13629920c0a3a376eb7bda4699edec6fc888b61
  url: https://files.pythonhosted.org/packages/e2/89/bbf49656c0f02d9db40a2dfe2d7e1a3de0fd3cfbfa63c50ebcf75eebf4af/perutils-0.0.22.tar.gz
about:
  dev_url: https://Isaac.Flath@gmail.com.github.io
  doc_url: https://Isaac.Flath@gmail.com.github.io
  home: https://Isaac.Flath@gmail.com.github.io
  license: Apache Software
  license_family: APACHE
  summary: Isaacs personal utils
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - Isaac.Flath@gmail.com
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - fastai
  run:
  - pip
  - python
  - packaging
  - pandas
  - fastai
test:
  imports:
  - perutils
